
import type { Atom } from './types';

export const ATOMS: Omit<Atom, 'instanceId' | 'x' | 'y'>[] = [
  // 1-10
  { id: 'H', name: 'هيدروجين', symbol: 'H', color: 'bg-green-500', textColor: 'text-white', radius: 20, valency: '+1, -1' },
  { id: 'He', name: 'هيليوم', symbol: 'He', color: 'bg-indigo-500', textColor: 'text-white', radius: 21, valency: '0' },
  { id: 'Li', name: 'ليثيوم', symbol: 'Li', color: 'bg-red-500', textColor: 'text-white', radius: 23, valency: '+1' },
  { id: 'Be', name: 'بيريليوم', symbol: 'Be', color: 'bg-orange-500', textColor: 'text-white', radius: 25, valency: '+2' },
  { id: 'B', name: 'بورون', symbol: 'B', color: 'bg-teal-500', textColor: 'text-white', radius: 26, valency: '+3' },
  { id: 'C', name: 'كربون', symbol: 'C', color: 'bg-green-500', textColor: 'text-white', radius: 30, valency: '+4, -4' },
  { id: 'N', name: 'نيتروجين', symbol: 'N', color: 'bg-green-500', textColor: 'text-white', radius: 28, valency: '-3' },
  { id: 'O', name: 'أكسجين', symbol: 'O', color: 'bg-green-500', textColor: 'text-white', radius: 28, valency: '-2' },
  { id: 'F', name: 'فلور', symbol: 'F', color: 'bg-purple-500', textColor: 'text-white', radius: 24, valency: '-1' },
  { id: 'Ne', name: 'نيون', symbol: 'Ne', color: 'bg-indigo-500', textColor: 'text-white', radius: 24, valency: '0' },

  // 11-20
  { id: 'Na', name: 'صوديوم', symbol: 'Na', color: 'bg-red-500', textColor: 'text-white', radius: 28, valency: '+1' },
  { id: 'Mg', name: 'مغنيسيوم', symbol: 'Mg', color: 'bg-orange-500', textColor: 'text-white', radius: 32, valency: '+2' },
  { id: 'Al', name: 'ألومنيوم', symbol: 'Al', color: 'bg-blue-400', textColor: 'text-white', radius: 32, valency: '+3' },
  { id: 'Si', name: 'سيليكون', symbol: 'Si', color: 'bg-teal-500', textColor: 'text-white', radius: 33, valency: '+4' },
  { id: 'P', name: 'فوسفور', symbol: 'P', color: 'bg-green-500', textColor: 'text-white', radius: 32, valency: '-3, +5' },
  { id: 'S', name: 'كبريت', symbol: 'S', color: 'bg-green-500', textColor: 'text-white', radius: 32, valency: '-2, +6' },
  { id: 'Cl', name: 'كلور', symbol: 'Cl', color: 'bg-purple-500', textColor: 'text-white', radius: 30, valency: '-1' },
  { id: 'Ar', name: 'أرغون', symbol: 'Ar', color: 'bg-indigo-500', textColor: 'text-white', radius: 30, valency: '0' },
  { id: 'K', name: 'بوتاسيوم', symbol: 'K', color: 'bg-red-500', textColor: 'text-white', radius: 36, valency: '+1' },
  { id: 'Ca', name: 'كالسيوم', symbol: 'Ca', color: 'bg-orange-500', textColor: 'text-white', radius: 38, valency: '+2' },

  // 21-30
  { id: 'Sc', name: 'سكانديوم', symbol: 'Sc', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+3' },
  { id: 'Ti', name: 'تيتانيوم', symbol: 'Ti', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+4' },
  { id: 'V', name: 'فاناديوم', symbol: 'V', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+5' },
  { id: 'Cr', name: 'كروم', symbol: 'Cr', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+3, +6' },
  { id: 'Mn', name: 'منغنيز', symbol: 'Mn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+2, +4, +7' },
  { id: 'Fe', name: 'حديد', symbol: 'Fe', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+2, +3' },
  { id: 'Co', name: 'كوبالت', symbol: 'Co', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+2, +3' },
  { id: 'Ni', name: 'نيكل', symbol: 'Ni', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+2' },
  { id: 'Cu', name: 'نحاس', symbol: 'Cu', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+1, +2' },
  { id: 'Zn', name: 'زنك', symbol: 'Zn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 33, valency: '+2' },

  // 31-40
  { id: 'Ga', name: 'غاليوم', symbol: 'Ga', color: 'bg-blue-400', textColor: 'text-white', radius: 33, valency: '+3' },
  { id: 'Ge', name: 'جرمانيوم', symbol: 'Ge', color: 'bg-teal-500', textColor: 'text-white', radius: 33, valency: '+4' },
  { id: 'As', name: 'زرنيخ', symbol: 'As', color: 'bg-teal-500', textColor: 'text-white', radius: 33, valency: '-3, +3, +5' },
  { id: 'Se', name: 'سيلينيوم', symbol: 'Se', color: 'bg-green-500', textColor: 'text-white', radius: 33, valency: '-2, +4, +6' },
  { id: 'Br', name: 'بروم', symbol: 'Br', color: 'bg-purple-500', textColor: 'text-white', radius: 32, valency: '-1' },
  { id: 'Kr', name: 'كريبتون', symbol: 'Kr', color: 'bg-indigo-500', textColor: 'text-white', radius: 32, valency: '0' },
  { id: 'Rb', name: 'روبيديوم', symbol: 'Rb', color: 'bg-red-500', textColor: 'text-white', radius: 40, valency: '+1' },
  { id: 'Sr', name: 'سترونشيوم', symbol: 'Sr', color: 'bg-orange-500', textColor: 'text-white', radius: 40, valency: '+2' },
  { id: 'Y', name: 'يتريوم', symbol: 'Y', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+3' },
  { id: 'Zr', name: 'زركونيوم', symbol: 'Zr', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+4' },

  // 41-50
  { id: 'Nb', name: 'نيوبيوم', symbol: 'Nb', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+5' },
  { id: 'Mo', name: 'موليبدنوم', symbol: 'Mo', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+6' },
  { id: 'Tc', name: 'تكنشيوم', symbol: 'Tc', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+7' },
  { id: 'Ru', name: 'روثينيوم', symbol: 'Ru', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+3, +4' },
  { id: 'Rh', name: 'روديوم', symbol: 'Rh', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+3' },
  { id: 'Pd', name: 'بالاديوم', symbol: 'Pd', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+2, +4' },
  { id: 'Ag', name: 'فضة', symbol: 'Ag', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+1' },
  { id: 'Cd', name: 'كادميوم', symbol: 'Cd', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+2' },
  { id: 'In', name: 'إنديوم', symbol: 'In', color: 'bg-blue-400', textColor: 'text-white', radius: 35, valency: '+3' },
  { id: 'Sn', name: 'قصدير', symbol: 'Sn', color: 'bg-blue-400', textColor: 'text-white', radius: 35, valency: '+2, +4' },

  // 51-60
  { id: 'Sb', name: 'أنتيمون', symbol: 'Sb', color: 'bg-teal-500', textColor: 'text-white', radius: 35, valency: '+3, +5' },
  { id: 'Te', name: 'تيلوريوم', symbol: 'Te', color: 'bg-teal-500', textColor: 'text-white', radius: 35, valency: '-2, +4, +6' },
  { id: 'I', name: 'يود', symbol: 'I', color: 'bg-purple-500', textColor: 'text-white', radius: 34, valency: '-1' },
  { id: 'Xe', name: 'زينون', symbol: 'Xe', color: 'bg-indigo-500', textColor: 'text-white', radius: 34, valency: '0' },
  { id: 'Cs', name: 'سيزيوم', symbol: 'Cs', color: 'bg-red-500', textColor: 'text-white', radius: 44, valency: '+1' },
  { id: 'Ba', name: 'باريوم', symbol: 'Ba', color: 'bg-orange-500', textColor: 'text-white', radius: 44, valency: '+2' },
  { id: 'La', name: 'لانثانوم', symbol: 'La', color: 'bg-pink-400', textColor: 'text-white', radius: 38, valency: '+3' },
  { id: 'Ce', name: 'سيريوم', symbol: 'Ce', color: 'bg-pink-400', textColor: 'text-white', radius: 38, valency: '+3, +4' },
  { id: 'Pr', name: 'براسيوديميوم', symbol: 'Pr', color: 'bg-pink-400', textColor: 'text-white', radius: 38, valency: '+3' },
  { id: 'Nd', name: 'نيوديميوم', symbol: 'Nd', color: 'bg-pink-400', textColor: 'text-white', radius: 38, valency: '+3' },

  // 61-70
  { id: 'Pm', name: 'بروميثيوم', symbol: 'Pm', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Sm', name: 'ساماريوم', symbol: 'Sm', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+2, +3' },
  { id: 'Eu', name: 'أوروبيوم', symbol: 'Eu', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+2, +3' },
  { id: 'Gd', name: 'جادولينيوم', symbol: 'Gd', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Tb', name: 'تيربيوم', symbol: 'Tb', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Dy', name: 'ديسبروزيوم', symbol: 'Dy', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Ho', name: 'هولميوم', symbol: 'Ho', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Er', name: 'إربيوم', symbol: 'Er', color: 'bg-pink-400', textColor: 'text-white', radius: 37, valency: '+3' },
  { id: 'Tm', name: 'ثوليوم', symbol: 'Tm', color: 'bg-pink-400', textColor: 'text-white', radius: 36, valency: '+3' },
  { id: 'Yb', name: 'يتيربيوم', symbol: 'Yb', color: 'bg-pink-400', textColor: 'text-white', radius: 36, valency: '+2, +3' },

  // 71-80
  { id: 'Lu', name: 'لوتيشيوم', symbol: 'Lu', color: 'bg-pink-400', textColor: 'text-white', radius: 36, valency: '+3' },
  { id: 'Hf', name: 'هافنيوم', symbol: 'Hf', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+4' },
  { id: 'Ta', name: 'تانتالوم', symbol: 'Ta', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+5' },
  { id: 'W', name: 'تنجستن', symbol: 'W', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+6' },
  { id: 'Re', name: 'رينيوم', symbol: 'Re', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+7' },
  { id: 'Os', name: 'أوزميوم', symbol: 'Os', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+4' },
  { id: 'Ir', name: 'إريديوم', symbol: 'Ir', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+4' },
  { id: 'Pt', name: 'بلاتين', symbol: 'Pt', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 34, valency: '+2, +4' },
  { id: 'Au', name: 'ذهب', symbol: 'Au', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+1, +3' },
  { id: 'Hg', name: 'زئبق', symbol: 'Hg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 35, valency: '+1, +2' },

  // 81-90
  { id: 'Tl', name: 'ثاليوم', symbol: 'Tl', color: 'bg-blue-400', textColor: 'text-white', radius: 35, valency: '+1, +3' },
  { id: 'Pb', name: 'رصاص', symbol: 'Pb', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: '+2, +4' },
  { id: 'Bi', name: 'بزموت', symbol: 'Bi', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: '+3, +5' },
  { id: 'Po', name: 'بولونيوم', symbol: 'Po', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: '+2, +4' },
  { id: 'At', name: 'أستاتين', symbol: 'At', color: 'bg-purple-500', textColor: 'text-white', radius: 35, valency: '-1' },
  { id: 'Rn', name: 'رادون', symbol: 'Rn', color: 'bg-indigo-500', textColor: 'text-white', radius: 35, valency: '0' },
  { id: 'Fr', name: 'فرانسيوم', symbol: 'Fr', color: 'bg-red-500', textColor: 'text-white', radius: 46, valency: '+1' },
  { id: 'Ra', name: 'راديوم', symbol: 'Ra', color: 'bg-orange-500', textColor: 'text-white', radius: 46, valency: '+2' },
  { id: 'Ac', name: 'أكتينيوم', symbol: 'Ac', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+3' },
  { id: 'Th', name: 'ثوريوم', symbol: 'Th', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+4' },

  // 91-100
  { id: 'Pa', name: 'بروتاكتينيوم', symbol: 'Pa', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+5' },
  { id: 'U', name: 'يورانيوم', symbol: 'U', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+4, +6' },
  { id: 'Np', name: 'نبتونيوم', symbol: 'Np', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+5' },
  { id: 'Pu', name: 'بلوتونيوم', symbol: 'Pu', color: 'bg-rose-400', textColor: 'text-white', radius: 40, valency: '+4, +6' },
  { id: 'Am', name: 'أمريسيوم', symbol: 'Am', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3, +4' },
  { id: 'Cm', name: 'كوريوم', symbol: 'Cm', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3' },
  { id: 'Bk', name: 'بركليوم', symbol: 'Bk', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3, +4' },
  { id: 'Cf', name: 'كاليفورنيوم', symbol: 'Cf', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3' },
  { id: 'Es', name: 'أينشتاينيوم', symbol: 'Es', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3' },
  { id: 'Fm', name: 'فيرميوم', symbol: 'Fm', color: 'bg-rose-400', textColor: 'text-white', radius: 39, valency: '+3' },

  // 101-110
  { id: 'Md', name: 'مندليفيوم', symbol: 'Md', color: 'bg-rose-400', textColor: 'text-white', radius: 38, valency: '+2, +3' },
  { id: 'No', name: 'نوبليوم', symbol: 'No', color: 'bg-rose-400', textColor: 'text-white', radius: 38, valency: '+2, +3' },
  { id: 'Lr', name: 'لورنسيوم', symbol: 'Lr', color: 'bg-rose-400', textColor: 'text-white', radius: 38, valency: '+3' },
  { id: 'Rf', name: 'رذرفورديوم', symbol: 'Rf', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+4' },
  { id: 'Db', name: 'دوبنيوم', symbol: 'Db', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+5' },
  { id: 'Sg', name: 'سيبورغيوم', symbol: 'Sg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+6' },
  { id: 'Bh', name: 'بوريوم', symbol: 'Bh', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+7' },
  { id: 'Hs', name: 'هاسيوم', symbol: 'Hs', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 37, valency: '+8' },
  { id: 'Mt', name: 'مايتنريوم', symbol: 'Mt', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: 'N/A' },
  { id: 'Ds', name: 'دارمشتاديوم', symbol: 'Ds', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: 'N/A' },

  // 111-118
  { id: 'Rg', name: 'رونتجينيوم', symbol: 'Rg', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: 'N/A' },
  { id: 'Cn', name: 'كوبرنيسيوم', symbol: 'Cn', color: 'bg-yellow-500', textColor: 'text-slate-800', radius: 36, valency: '+2' },
  { id: 'Nh', name: 'نيهونيوم', symbol: 'Nh', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: 'N/A' },
  { id: 'Fl', name: 'فليروفيوم', symbol: 'Fl', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: 'N/A' },
  { id: 'Mc', name: 'موسكوفيوم', symbol: 'Mc', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: 'N/A' },
  { id: 'Lv', name: 'ليفرموريوم', symbol: 'Lv', color: 'bg-blue-400', textColor: 'text-white', radius: 36, valency: 'N/A' },
  { id: 'Ts', name: 'تينيسين', symbol: 'Ts', color: 'bg-purple-500', textColor: 'text-white', radius: 36, valency: 'N/A' },
  { id: 'Og', name: 'أوغانيسون', symbol: 'Og', color: 'bg-indigo-500', textColor: 'text-white', radius: 36, valency: '0' },

  // Polyatomic Ions - bg-cyan-600
  { id: 'SO4', name: 'كبريتات', symbol: 'SO₄²⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 40, valency: '-2' },
  { id: 'NO3', name: 'نترات', symbol: 'NO₃⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 38, valency: '-1' },
  { id: 'OH', name: 'هيدروكسيد', symbol: 'OH⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 35, valency: '-1' },
  { id: 'NH4', name: 'أمونيوم', symbol: 'NH₄⁺', color: 'bg-cyan-600', textColor: 'text-white', radius: 38, valency: '+1' },
  { id: 'CO3', name: 'كربونات', symbol: 'CO₃²⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 40, valency: '-2' },
  { id: 'PO4', name: 'فوسفات', symbol: 'PO₄³⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 42, valency: '-3' },
  { id: 'CN', name: 'سيانيد', symbol: 'CN⁻', color: 'bg-cyan-600', textColor: 'text-white', radius: 35, valency: '-1' },
];

export const COMMON_COMPOUNDS: { name: string; formula: string }[] = [
  { name: 'ماء', formula: 'H₂O' },
  { name: 'ملح الطعام', formula: 'NaCl' },
  { name: 'ثاني أكسيد الكربون', formula: 'CO₂' },
  { name: 'حمض الهيدروكلوريك', formula: 'HCl' },
  { name: 'حمض الكبريتيك', formula: 'H₂SO₄' },
  { name: 'هيدروكسيد الصوديوم', formula: 'NaOH' },
  { name: 'أمونيا', formula: 'NH₃' },
  { name: 'ميثان', formula: 'CH₄' },
  { name: 'بنزين', formula: 'C₆H₆' },
  { name: 'كربونات الكالسيوم', formula: 'CaCO₃' },
  { name: 'حمض الخليك', formula: 'CH₃COOH' },
  { name: 'جلوكوز', formula: 'C₆H₁₂O₆' },
  { name: 'نترات البوتاسيوم', formula: 'KNO₃' },
  { name: 'أكسيد الحديد (III)', formula: 'Fe₂O₃' },
  { name: 'بيكربونات الصوديوم', formula: 'NaHCO₃' },
  { name: 'برمنجنات البوتاسيوم', formula: 'KMnO₄' },
  { name: 'ثاني كرومات البوتاسيوم', formula: 'K₂Cr₂O₇' },
  { name: 'نترات الفضة', formula: 'AgNO₃' },
  { name: 'كبريتات النحاس (II)', formula: 'CuSO₄' },
  { name: 'إيثانول', formula: 'C₂H₅OH' },
  { name: 'أسيتون', formula: 'CH₃COCH₃' },
  { name: 'يوديد البوتاسيوم', formula: 'KI' },
  { name: 'بيروكسيد الهيدروجين', formula: 'H₂O₂' },
  { name: 'حمض النيتريك', formula: 'HNO₃' },
  { name: 'حمض الفوسفوريك', formula: 'H₃PO₄' },
  { name: 'هيبوكلوريت الصوديوم', formula: 'NaClO' },
  { name: 'كلورات البوتاسيوم', formula: 'KClO₃' },
  { name: 'أكسيد الكالسيوم', formula: 'CaO' },
  { name: 'كبريتات الحديد (II)', formula: 'FeSO₄' },
  { name: 'كبريتات الباريوم', formula: 'BaSO₄' },
  { name: 'كلوريد الألومنيوم', formula: 'AlCl₃' },
  { name: 'خامس أكسيد الفوسفور', formula: 'P₄O₁₀' },
  { name: 'ثاني أكسيد الكبريت', formula: 'SO₂' },
  { name: 'كبريتيد الهيدروجين', formula: 'H₂S' },
  { name: 'كربونات المغنيسيوم', formula: 'MgCO₃' },
  { name: 'كلوريد الفضة', formula: 'AgCl' },
  { name: 'يوديد الرصاص (II)', formula: 'PbI₂' },
  { name: 'نترات النحاس (II)', formula: 'Cu(NO₃)₂' },
  { name: 'كبريتات الأمونيوم', formula: '(NH₄)₂SO₄' },
  { name: 'كربونات الليثيوم', formula: 'Li₂CO₃' },
  { name: 'كلوريد النيكل (II)', formula: 'NiCl₂' },
  { name: 'حمض الهيدروفلوريك', formula: 'HF' },
];

export const ORGANIC_PRESETS = [
    { name: 'ميثان', formula: 'CH₄', family: 'ألكان' },
    { name: 'إيثان', formula: 'C₂H₆', family: 'ألكان' },
    { name: 'بروبان', formula: 'C₃H₈', family: 'ألكان' },
    { name: 'بيوتان', formula: 'C₄H₁₀', family: 'ألكان' },
    { name: 'بنتان', formula: 'C₅H₁2', family: 'ألكان' },
    { name: 'إيثيلين', formula: 'C₂H₄', family: 'ألكين' },
    { name: 'بروبيلين', formula: 'C₃H₆', family: 'ألكين' },
    { name: 'أسيتيلين', formula: 'C₂H₂', family: 'ألكاين' },
    { name: 'إيثانول', formula: 'C₂H₅OH', family: 'كحول' },
    { name: 'ميثانول', formula: 'CH₃OH', family: 'كحول' },
    { name: 'إيزوبروبانول', formula: 'C₃H₈O', family: 'كحول' },
    { name: 'حمض الخليك', formula: 'CH₃COOH', family: 'حمض كربوكسيلي' },
    { name: 'بنزين', formula: 'C₆H₆', family: 'حلقة بنزين' },
    { name: 'تولوين', formula: 'C₇H₈', family: 'حلقة بنزين' },
    { name: 'أسيتون', formula: 'CH₃COCH₃', family: 'كيتون' },
    { name: 'فورمالدهيد', formula: 'HCHO', family: 'ألدهيد' },
    { name: 'كلوروفورم', formula: 'CHCl₃', family: 'هاليد الألكيل' },
    { name: 'يوريا', formula: 'CH₄N₂O', family: 'أميد' },
    { name: 'أسبرين', formula: 'C₉H₈O₄', family: 'إستر' },
    { name: 'كافيين', formula: 'C₈H₁₀N₄O₂', family: 'ألكالويد' },
    { name: 'نيكوتين', formula: 'C₁₀H₁₄N₂', family: 'ألكالويد' },
    { name: 'جليسرول', formula: 'C₃H₈O₃', family: 'كحول متعدد' },
    { name: 'إيثيلين جليكول', formula: 'C₂H₆O₂', family: 'كحول ثنائي' },
    { name: 'حمض الستريك', formula: 'C₆H₈O₇', family: 'حمض كربوكسيلي' },
];

export const BATTERY_PRESETS = [
    { id: 'li-ion-c', name: 'ليثيوم أيون (أكسيد الكوبالت)', type: 'Li-ion (LCO)' },
    { id: 'li-ion-p', name: 'ليثيوم حديد فوسفات', type: 'Li-ion (LFP)' },
    { id: 'lead-acid', name: 'رصاص حمضية (سيارات)', type: 'Lead-Acid' },
    { id: 'nimh', name: 'نيكل ميتال هيدريد', type: 'NiMH' },
    { id: 'alkaline', name: 'قلوية (ريموت)', type: 'Alkaline' },
    { id: 'zinc-carbon', name: 'زنك-كربون', type: 'Zinc-Carbon' },
    { id: 'solid-state', name: 'بطارية الحالة الصلبة', type: 'Solid State' },
    { id: 'sodium-ion', name: 'أيونات الصوديوم', type: 'Na-ion' },
];

export const ORGANIC_FAMILIES = [
  'ألكان', 'ألكين', 'ألكاين', 'ألكان حلقي', 'حلقة بنزين', 'كحول', 'هاليد الألكيل', 'إيثر', 'أمين', 'ألدهيد', 'كيتون', 'حمض كربوكسيلي', 'إستر', 'أميد'
];
