
import type { Atom } from './types';

export const ELEMENT_DATA: Record<string, { name: string; symbol: string; color: string; type?: 'atom' | 'ion' }> = {
  'H': { name: 'هيدروجين', symbol: 'H', color: 'bg-slate-200' },
  'He': { name: 'هيليوم', symbol: 'He', color: 'bg-indigo-300' },
  'Li': { name: 'ليثيوم', symbol: 'Li', color: 'bg-red-400' },
  'Be': { name: 'بيريليوم', symbol: 'Be', color: 'bg-orange-400' },
  'B': { name: 'بورون', symbol: 'B', color: 'bg-teal-400' },
  'C': { name: 'كربون', symbol: 'C', color: 'bg-slate-700' },
  'N': { name: 'نيتروجين', symbol: 'N', color: 'bg-blue-300' },
  'O': { name: 'أكسجين', symbol: 'O', color: 'bg-blue-400' },
  'F': { name: 'فلور', symbol: 'F', color: 'bg-yellow-300' },
  'Ne': { name: 'نيون', symbol: 'Ne', color: 'bg-indigo-300' },
  'Na': { name: 'صوديوم', symbol: 'Na', color: 'bg-red-400' },
  'Mg': { name: 'مغنيسيوم', symbol: 'Mg', color: 'bg-orange-400' },
  'Al': { name: 'ألومنيوم', symbol: 'Al', color: 'bg-slate-300' },
  'Si': { name: 'سيليكون', symbol: 'Si', color: 'bg-teal-600' },
  'P': { name: 'فوسفور', symbol: 'P', color: 'bg-orange-300' },
  'S': { name: 'كبريت', symbol: 'S', color: 'bg-yellow-400' },
  'Cl': { name: 'كلور', symbol: 'Cl', color: 'bg-green-300' },
  'Ar': { name: 'أرغون', symbol: 'Ar', color: 'bg-indigo-300' },
  'K': { name: 'بوتاسيوم', symbol: 'K', color: 'bg-red-400' },
  'Ca': { name: 'كالسيوم', symbol: 'Ca', color: 'bg-orange-400' },
  'Sc': { name: 'سكانديوم', symbol: 'Sc', color: 'bg-slate-400' },
  'Ti': { name: 'تيتانيوم', symbol: 'Ti', color: 'bg-slate-400' },
  'V': { name: 'فاناديوم', symbol: 'V', color: 'bg-slate-400' },
  'Cr': { name: 'كروم', symbol: 'Cr', color: 'bg-blue-200' },
  'Mn': { name: 'منغنيز', symbol: 'Mn', color: 'bg-pink-300' },
  'Fe': { name: 'حديد', symbol: 'Fe', color: 'bg-slate-500' },
  'Co': { name: 'كوبالت', symbol: 'Co', color: 'bg-blue-600' },
  'Ni': { name: 'نيكل', symbol: 'Ni', color: 'bg-green-600' },
  'Cu': { name: 'نحاس', symbol: 'Cu', color: 'bg-orange-600' },
  'Zn': { name: 'خارصين', symbol: 'Zn', color: 'bg-slate-300' },
  'Ga': { name: 'غاليوم', symbol: 'Ga', color: 'bg-slate-300' },
  'Ge': { name: 'جرمانيوم', symbol: 'Ge', color: 'bg-slate-300' },
  'As': { name: 'زرنيخ', symbol: 'As', color: 'bg-emerald-400' },
  'Se': { name: 'سيلينيوم', symbol: 'Se', color: 'bg-green-400' },
  'Br': { name: 'بروم', symbol: 'Br', color: 'bg-red-800' },
  'Kr': { name: 'كريبتون', symbol: 'Kr', color: 'bg-indigo-300' },
  'Rb': { name: 'روبيديوم', symbol: 'Rb', color: 'bg-red-400' },
  'Sr': { name: 'سترونشيوم', symbol: 'Sr', color: 'bg-orange-400' },
  'Y': { name: 'يتريوم', symbol: 'Y', color: 'bg-slate-400' },
  'Zr': { name: 'زركونيوم', symbol: 'Zr', color: 'bg-slate-400' },
  'Nb': { name: 'نيوبيوم', symbol: 'Nb', color: 'bg-slate-400' },
  'Mo': { name: 'موليبدنوم', symbol: 'Mo', color: 'bg-slate-400' },
  'Tc': { name: 'تكنشيوم', symbol: 'Tc', color: 'bg-slate-400' },
  'Ru': { name: 'روثينيوم', symbol: 'Ru', color: 'bg-slate-400' },
  'Rh': { name: 'روديوم', symbol: 'Rh', color: 'bg-slate-400' },
  'Pd': { name: 'بالاديوم', symbol: 'Pd', color: 'bg-slate-300' },
  'Ag': { name: 'فضة', symbol: 'Ag', color: 'bg-slate-300' },
  'Cd': { name: 'كادميوم', symbol: 'Cd', color: 'bg-slate-300' },
  'In': { name: 'إنديوم', symbol: 'In', color: 'bg-slate-300' },
  'Sn': { name: 'قصدير', symbol: 'Sn', color: 'bg-slate-300' },
  'Sb': { name: 'أنتيمون', symbol: 'Sb', color: 'bg-slate-300' },
  'Te': { name: 'تيلوريوم', symbol: 'Te', color: 'bg-slate-300' },
  'I': { name: 'يود', symbol: 'I', color: 'bg-purple-800' },
  'Xe': { name: 'زينون', symbol: 'Xe', color: 'bg-indigo-300' },
  'Cs': { name: 'سيزيوم', symbol: 'Cs', color: 'bg-red-400' },
  'Ba': { name: 'باريوم', symbol: 'Ba', color: 'bg-orange-400' },
  'La': { name: 'لانثانوم', symbol: 'La', color: 'bg-slate-400' },
  'Ce': { name: 'سيريوم', symbol: 'Ce', color: 'bg-slate-400' },
  'Pr': { name: 'براسوديميوم', symbol: 'Pr', color: 'bg-slate-400' },
  'Nd': { name: 'نيوديميوم', symbol: 'Nd', color: 'bg-slate-400' },
  'Pm': { name: 'بروميثيوم', symbol: 'Pm', color: 'bg-slate-400' },
  'Sm': { name: 'ساماريوم', symbol: 'Sm', color: 'bg-slate-400' },
  'Eu': { name: 'أوروبيوم', symbol: 'Eu', color: 'bg-slate-400' },
  'Gd': { name: 'جادولينيوم', symbol: 'Gd', color: 'bg-slate-400' },
  'Tb': { name: 'تيربيوم', symbol: 'Tb', color: 'bg-slate-400' },
  'Dy': { name: 'ديسبروزيوم', symbol: 'Dy', color: 'bg-slate-400' },
  'Ho': { name: 'هولميوم', symbol: 'Ho', color: 'bg-slate-400' },
  'Er': { name: 'إربيوم', symbol: 'Er', color: 'bg-slate-400' },
  'Tm': { name: 'ثوليوم', symbol: 'Tm', color: 'bg-slate-400' },
  'Yb': { name: 'يتيربيوم', symbol: 'Yb', color: 'bg-slate-400' },
  'Lu': { name: 'لوتيشيوم', symbol: 'Lu', color: 'bg-slate-400' },
  'Hf': { name: 'هافنيوم', symbol: 'Hf', color: 'bg-slate-400' },
  'Ta': { name: 'تانتالوم', symbol: 'Ta', color: 'bg-slate-400' },
  'W': { name: 'تنجستن', symbol: 'W', color: 'bg-slate-400' },
  'Re': { name: 'رينيوم', symbol: 'Re', color: 'bg-slate-400' },
  'Os': { name: 'أوزميوم', symbol: 'Os', color: 'bg-slate-400' },
  'Ir': { name: 'إريديوم', symbol: 'Ir', color: 'bg-slate-400' },
  'Pt': { name: 'بلاتين', symbol: 'Pt', color: 'bg-slate-200' },
  'Au': { name: 'ذهب', symbol: 'Au', color: 'bg-yellow-600' },
  'Hg': { name: 'زئبق', symbol: 'Hg', color: 'bg-slate-400' },
  'Tl': { name: 'ثاليوم', symbol: 'Tl', color: 'bg-slate-300' },
  'Pb': { name: 'رصاص', symbol: 'Pb', color: 'bg-slate-600' },
  'Bi': { name: 'بزموت', symbol: 'Bi', color: 'bg-slate-300' },
  'Po': { name: 'بولونيوم', symbol: 'Po', color: 'bg-slate-300' },
  'At': { name: 'أستاتين', symbol: 'At', color: 'bg-slate-300' },
  'Rn': { name: 'رادون', symbol: 'Rn', color: 'bg-indigo-300' },
  'Fr': { name: 'فرانسيوم', symbol: 'Fr', color: 'bg-red-400' },
  'Ra': { name: 'راديوم', symbol: 'Ra', color: 'bg-orange-400' },
  'Ac': { name: 'أكتينيوم', symbol: 'Ac', color: 'bg-slate-400' },
  'Th': { name: 'ثوريوم', symbol: 'Th', color: 'bg-slate-400' },
  'Pa': { name: 'بروتاكتينيوم', symbol: 'Pa', color: 'bg-slate-400' },
  'U': { name: 'يورانيوم', symbol: 'U', color: 'bg-green-700' },
  'Np': { name: 'نبتونيوم', symbol: 'Np', color: 'bg-slate-400' },
  'Pu': { name: 'بلوتونيوم', symbol: 'Pu', color: 'bg-slate-400' },
  'Am': { name: 'أمريسيوم', symbol: 'Am', color: 'bg-slate-400' },
  'Cm': { name: 'كوريوم', symbol: 'Cm', color: 'bg-slate-400' },
  'Bk': { name: 'بيركليوم', symbol: 'Bk', color: 'bg-slate-400' },
  'Cf': { name: 'كاليفورنيوم', symbol: 'Cf', color: 'bg-slate-400' },
  'Es': { name: 'أينشتاينيوم', symbol: 'Es', color: 'bg-slate-400' },
  'Fm': { name: 'فيرميوم', symbol: 'Fm', color: 'bg-slate-400' },
  'Md': { name: 'مندليفيوم', symbol: 'Md', color: 'bg-slate-400' },
  'No': { name: 'نوبليوم', symbol: 'No', color: 'bg-slate-400' },
  'Lr': { name: 'لورنسيوم', symbol: 'Lr', color: 'bg-slate-400' },
  'Rf': { name: 'رذرفورديوم', symbol: 'Rf', color: 'bg-slate-400' },
  'Db': { name: 'دوبنيوم', symbol: 'Db', color: 'bg-slate-400' },
  'Sg': { name: 'سيبورغيوم', symbol: 'Sg', color: 'bg-slate-400' },
  'Bh': { name: 'بوريوم', symbol: 'Bh', color: 'bg-slate-400' },
  'Hs': { name: 'هاسيوم', symbol: 'Hs', color: 'bg-slate-400' },
  'Mt': { name: 'مايتنريوم', symbol: 'Mt', color: 'bg-slate-400' },
  'Ds': { name: 'دارمشتاتيوم', symbol: 'Ds', color: 'bg-slate-400' },
  'Rg': { name: 'رونتجينيوم', symbol: 'Rg', color: 'bg-slate-400' },
  'Cn': { name: 'كوبرنيسيوم', symbol: 'Cn', color: 'bg-slate-400' },
  'Nh': { name: 'نيهونيوم', symbol: 'Nh', color: 'bg-slate-400' },
  'Fl': { name: 'فليروفيوم', symbol: 'Fl', color: 'bg-slate-400' },
  'Mc': { name: 'موسكوفيوم', symbol: 'Mc', color: 'bg-slate-400' },
  'Lv': { name: 'ليفرموريوم', symbol: 'Lv', color: 'bg-slate-400' },
  'Ts': { name: 'تنسين', symbol: 'Ts', color: 'bg-slate-400' },
  'Og': { name: 'أوجانيسون', symbol: 'Og', color: 'bg-slate-400' },
  // Polyatomic Ions
  'OH-': { name: 'هيدروكسيد', symbol: 'OH⁻', color: 'bg-blue-100', type: 'ion' },
  'NO3-': { name: 'نيترات', symbol: 'NO₃⁻', color: 'bg-indigo-100', type: 'ion' },
  'SO4 2-': { name: 'كبريتات', symbol: 'SO₄²⁻', color: 'bg-yellow-100', type: 'ion' },
  'CO3 2-': { name: 'كربونات', symbol: 'CO₃²⁻', color: 'bg-slate-300', type: 'ion' },
  'PO4 3-': { name: 'فوسفات', symbol: 'PO₄³⁻', color: 'bg-orange-100', type: 'ion' },
  'NH4+': { name: 'أمونيوم', symbol: 'NH₄⁺', color: 'bg-emerald-100', type: 'ion' },
};

export const COMMON_COMPOUNDS = [
  { name: 'ماء', formula: 'H2O' },
  { name: 'ثاني أكسيد الكربون', formula: 'CO2' },
  { name: 'ملح الطعام', formula: 'NaCl' },
  { name: 'أمونيا', formula: 'NH3' },
  { name: 'حمض الكبريتيك', formula: 'H2SO4' },
  { name: 'حمض الهيدروكلوريك', formula: 'HCl' },
  { name: 'سكر الجلوكوز', formula: 'C6H12O6' },
  { name: 'إيثانول', formula: 'C2H5OH' },
  { name: 'ميثان', formula: 'CH4' },
  { name: 'بنزين', formula: 'C6H6' },
];

export const ATOMS: Omit<Atom, 'instanceId' | 'x' | 'y'>[] = Object.keys(ELEMENT_DATA).map((symbol) => {
  const existing = ELEMENT_DATA[symbol];
  return {
    id: symbol,
    name: existing.name,
    symbol: existing.symbol,
    color: existing.color,
    textColor: symbol === 'C' || symbol === 'Pb' || symbol === 'U' || symbol === 'I' || symbol === 'Br' || symbol === 'S' ? 'text-white' : 'text-slate-800',
    radius: existing.type === 'ion' ? 28 : 22,
    electronConfiguration: '---',
  };
});

export const ORGANIC_FAMILIES = [
  'ألكان', 'ألكين', 'ألكاين', 'كحول', 'حمض كربوكسيلي', 'كيتون', 'ألديهيد', 'إستر', 'أمين', 'إيثر'
];

export const ORGANIC_SUBSTITUENTS = [
  'بدون', 'هيدروكسيل (OH)', 'كربونيل (C=O)', 'كربوكسيل (COOH)', 'أمين (NH2)', 'هالوجين (Cl)', 'هالوجين (F)', 'نيترو (NO2)', 'ميثيل (CH3)', 'فينيل (C6H5)'
];

export const BIO_SUGGESTIONS = {
  carbs: ['جلوكوز', 'فركتوز', 'سكروز', 'نشا', 'سليلوز'],
  proteins: ['جلايسين', 'ألانين', 'فالين', 'فينيل ألانين', 'تريبتوفان'],
  fats: ['ثلاثي الغليسريد', 'كوليسترول', 'حمض البالمتيك'],
};

export const ELECTRODES = ['Zn', 'Cu', 'Ag', 'Mg', 'Al', 'Pb', 'Fe', 'Ni', 'Sn', 'Au', 'Pt', 'Li', 'K', 'Ca', 'Na'];

export const SUGGESTIONS = {
  thermochemistry: ['احتراق الميثان', 'تفكك كربونات الكالسيوم', 'تفاعل هابر-بوش', 'التمثيل الضوئي'],
  solution: ['NaCl في الماء', 'حمض الخليك في الماء', 'إيثانول في الماء'],
  batteries: ['بطارية ليثيوم أيون (Li-ion)', 'بطارية الرصاص الحمضية (Lead-Acid)', 'بطارية قلوية (Alkaline)', 'بطارية نيكل-كادميوم (Ni-Cd)', 'بطارية نيكل-هيدريد فلز (Ni-MH)', 'بطارية زنك-كربون (Zinc-Carbon)', 'بطارية ليثيوم بوليمر (Li-Po)', 'بطارية فوسفات حديد الليثيوم (LiFePO4)', 'بطارية الحالة الصلبة (Solid-State)'],
  history: ['اكتشاف الراديوم', 'جدول مندليف', 'نموذج رذرفورد الذري', 'تاريخ الأنسولين'],
};
